# Generated by Django 5.1.2 on 2024-11-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'categorias_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id_dia_semana', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'diassemana_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.BooleanField()),
                ('menu', models.BooleanField()),
                ('nome', models.CharField(max_length=100)),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'produtos_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensCategorias',
            fields=[
                ('id_item_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'itenscategorias_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensMenus',
            fields=[
                ('id_item_menu', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'itensmenus_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensOpcoes',
            fields=[
                ('id_item_opcao', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'itensopcoes_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensTipos',
            fields=[
                ('id_item_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'itenstipos_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenusDiasSemana',
            fields=[
                ('id_menu_dia_semana', models.AutoField(primary_key=True, serialize=False)),
                ('almoco', models.BooleanField()),
                ('jantar', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'menusdiassemana_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('id_opcao', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'opcoes_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tipos_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id_item', models.OneToOneField(db_column='id_item', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='produto_item', serialize=False, to='produtos.produtos')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'itens_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id_menu', models.OneToOneField(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='produto_menu', serialize=False, to='produtos.produtos')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'menus_view',
                'managed': False,
            },
        ),
    ]
