# Generated by Django 5.1.2 on 2024-11-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemcategoria',
            table='itemcategoria',
        ),
        migrations.AlterModelTable(
            name='itemtipo',
            table='itemtipo',
        ),
        migrations.AlterModelTable(
            name='menudiasemana',
            table='menudiasemana',
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='menuitem',
        ),
        migrations.AlterModelTable(
            name='opcaoitem',
            table='opcaoitem',
        ),
    ]
