# Generated by Django 5.1.2 on 2024-11-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diassemana',
            table='diassemana',
        ),
        migrations.AlterModelTable(
            name='itenscategorias',
            table='itenscategorias',
        ),
        migrations.AlterModelTable(
            name='itensmenus',
            table='itensmenus',
        ),
        migrations.AlterModelTable(
            name='itensopcoes',
            table='itensopcoes',
        ),
        migrations.AlterModelTable(
            name='itenstipos',
            table='itenstipos',
        ),
        migrations.AlterModelTable(
            name='menusdiassemana',
            table='menusdiassemana',
        ),
    ]
