# Generated by Django 5.1.2 on 2024-11-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_itemcategoria_table_alter_itemtipo_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opcaoitem',
            table='itemopcao',
        ),
    ]
