# Generated by Django 5.1.2 on 2024-11-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_itemmenu_delete_menuitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmenu',
            table='itemmenu',
        ),
    ]
