CREATE TABLE IF NOT EXISTS estadosmesas (
	id_estado_mesa SERIAL PRIMARY KEY,
	designacao VARCHAR(20) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

/* CREATE TABLE IF NOT EXISTS utilizadores (
	id SERIAL PRIMARY KEY,
	turno_almoco BOOLEAN DEFAULT FALSE NOT NULL,
	turno_jantar BOOLEAN DEFAULT FALSE NOT NULL,
	data_nascimento DATE,
	genero VARCHAR(10) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); */

CREATE TABLE IF NOT EXISTS fornecedores (
	id_fornecedor SERIAL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	vende_ingredientes BOOLEAN DEFAULT FALSE NOT NULL,
	vende_utensilios BOOLEAN DEFAULT FALSE NOT NULL,
	morada VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	telemovel VARCHAR(20) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carrinhos (
	id_carrinho SERIAL PRIMARY KEY,
	preco_total DECIMAL(10, 2) NOT NULL DEFAULT 0,
	data_compra TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingredientes (
	id_ingrediente SERIAL PRIMARY KEY,
	id_fornecedor INT REFERENCES fornecedores(id_fornecedor) ON DELETE CASCADE,
	nome VARCHAR(255) NOT NULL,
	url_imagem VARCHAR(2048),
	quantidade_stock INT NOT NULL DEFAULT 0,
	unidade_medida VARCHAR(50) NOT NULL,
	limite_stock INT,
	preco DECIMAL(10, 2) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingredientescarrinhos (
	id_ingrediente_carrinho SERIAL PRIMARY KEY,
	id_ingrediente INT REFERENCES ingredientes(id_ingrediente) ON DELETE CASCADE,
	id_administrador INT REFERENCES utilizadores(id) ON DELETE CASCADE,
	id_carrinho INT REFERENCES carrinhos(id_carrinho) ON DELETE CASCADE,
	quantidade INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS utensilios (
	id_utensilio SERIAL PRIMARY KEY,
	id_fornecedor INT REFERENCES Fornecedor(id_fornecedor) ON DELETE CASCADE,
	nome VARCHAR(100) NOT NULL,
	url_imagem VARCHAR(2048),
	quantidade_stock INT NOT NULL DEFAULT 0,
	limite_stock INT,
	preco DECIMAL(10, 2) NOT NULL,
	id_fornecedor INT REFERENCES fornecedores(id_fornecedor) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS utensilioscarrinhos (
	id_utensilio_carrinho SERIAL PRIMARY KEY,
	id_utensilio INT REFERENCES utensilios(id_utensilio) ON DELETE CASCADE,
	id_administrador INT REFERENCES utilizadores(id) ON DELETE CASCADE,
	id_carrinho INT REFERENCES carrinhos(id_carrinho) ON DELETE CASCADE,
	quantidade INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receitas (
	id_receita SERIAL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	duracao INTERVAL NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingredientesreceitas (
	id_ingrediente_receita SERIAL PRIMARY KEY,
	id_ingrediente INT REFERENCES ingredientes(id_ingrediente) ON DELETE CASCADE,
	id_receita INT REFERENCES receitas(id_receita) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS utensiliosreceitas (
	id_utensilio_receita SERIAL PRIMARY KEY,
	id_utensilio INT REFERENCES utensilios(id_utensilio) ON DELETE CASCADE,
	id_receita INT REFERENCES receitas(id_receita) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instrucoes (
	id_instrucao SERIAL PRIMARY KEY,
	id_receita INT REFERENCES receitas(id_receita) ON DELETE CASCADE,
	numero_sequencia INT,
	descricao TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instrucoesingredientes (
	id_instrucao_ingrediente SERIAL PRIMARY KEY,
	id_instrucao INT REFERENCES Instrucao(id_instrucao) ON DELETE CASCADE,
	id_ingrediente INT REFERENCES Ingrediente(id_ingrediente) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instrucoesutensilios (
	id_instrucao_utensilio SERIAL PRIMARY KEY,
	id_instrucao INT REFERENCES Instrucao(id_instrucao) ON DELETE CASCADE,
	id_utensilio INT REFERENCES Utensilio(id_utensilio) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mesas (
	id_mesa SERIAL PRIMARY KEY,
	id_estado_mesa INT REFERENCES estadosmesas(id_estado_mesa) ON DELETE CASCADE,
	numero INT NOT NULL,
	capacidade_maxima INT NOT NULL,
	quantidade_clientes INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produtos (
	id_produto SERIAL PRIMARY KEY,
	item BOOLEAN DEFAULT FALSE NOT NULL,
	menu BOOLEAN DEFAULT FALSE NOT NULL,
	nome VARCHAR(100) NOT NULL,
	url_imagem VARCHAR(2048),
	preco DECIMAL(10, 2) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tipos (
	id_tipo SERIAL PRIMARY KEY,
	designacao VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Item (
	id_item INT PRIMARY KEY REFERENCES Produto(id_produto) ON DELETE CASCADE,
	porcao_unidade_medida VARCHAR(50) NOT NULL,
	porcao INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itenstipos (
	id_item_tipo SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_tipo INT REFERENCES tipos(id_tipo) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias (
	id_categoria SERIAL PRIMARY KEY,
	designacao VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itenscategorias (
	id_item_categoria SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_categoria INT REFERENCES categorias(id_categoria) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS opcoes (
	id_opcao SERIAL PRIMARY KEY,
	designacao VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itensopcoes (
	id_item_opcao SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_opcao INT REFERENCES opcoes(id_opcao) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS menus (
	id_menu INT PRIMARY KEY REFERENCES produtos(id_produto) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itensmenus (
	id_item_menu SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_menu INT REFERENCES menus(id_menu) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS diassemana (
	id_dia_semana SERIAL PRIMARY KEY,
	designacao VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS menusdiassemana (
	id_menu_dia_semana SERIAL PRIMARY KEY,
	id_menu INT REFERENCES Menu(id_menu) ON DELETE CASCADE,
	id_dia_semana INT REFERENCES DiaSemana(id_dia_semana) ON DELETE CASCADE,
	almoco BOOLEAN DEFAULT FALSE NOT NULL,
	jantar BOOLEAN DEFAULT FALSE NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS servicos (
	id_servico SERIAL PRIMARY KEY,
	id_garcom INT REFERENCES utilizadores(id) ON DELETE CASCADE,
	id_mesa INT REFERENCES mesas(id_mesa) ON DELETE CASCADE,
	data_hora_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_hora_fim TIMESTAMP,
	preco_total DECIMAL(10, 2) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pedidos (
	id_pedido SERIAL PRIMARY KEY,
	id_servico INT REFERENCES servicos(id_servico) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pedidosprodutos (
	id_pedido_produto SERIAL PRIMARY KEY,
	id_pedido INT REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
	id_produto INT REFERENCES produtos(id_produto) ON DELETE CASCADE,
	id_cozinheiro INT REFERENCES utilizadores(id) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pedidosprodutositensopcoes (
	id_pedido_produto_item_opcao SERIAL PRIMARY KEY,
	id_item_opcao INT REFERENCES itensopcoes(id_item_opcao) ON DELETE CASCADE,
	id_pedido_produto INT REFERENCES pedidosprodutos(id_pedido_produto) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservas (
	id_reserva SERIAL PRIMARY KEY,
	id_mesa INT REFERENCES mesas(id_mesa) ON DELETE CASCADE,
	data_hora TIMESTAMP NOT NULL,
	minutos_antes INTERVAL NOT NULL CHECK (minutos_antes >= '0 minutes' AND minutos_antes <= '120 minutes'),
	minutos_depois INTERVAL NOT NULL CHECK (minutos_depois >= '0 minutes' AND minutos_depois <= '120 minutes'),
	id_servico INT REFERENCES servicos(id_servico) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);