# Generated by Django 4.1.13 on 2024-10-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ingredientes', models.BooleanField(default=False)),
                ('utensilios', models.BooleanField(default=False)),
                ('morada', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('quantidade_stock', models.IntegerField()),
                ('unidade_medida', models.CharField(max_length=50)),
                ('limite_stock', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estimativaTempo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Utensilio',
            fields=[
                ('id_utensilio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('quantidade_stock', models.IntegerField()),
                ('limite_stock', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='UtensilioReceita',
            fields=[
                ('id_utensilioReceita', models.AutoField(primary_key=True, serialize=False)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.receita')),
                ('utensilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.utensilio')),
            ],
        ),
        migrations.CreateModel(
            name='UtensilioAdministrador',
            fields=[
                ('id_utensilioAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.administrador')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.carrinho')),
                ('utensilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.utensilio')),
            ],
        ),
        migrations.CreateModel(
            name='Instucao',
            fields=[
                ('id_instucao', models.AutoField(primary_key=True, serialize=False)),
                ('numeroSequencia', models.IntegerField()),
                ('descricao', models.TextField()),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.receita')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteValidade',
            fields=[
                ('id_ingredienteValidade', models.AutoField(primary_key=True, serialize=False)),
                ('data_validade', models.DateField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteAdministrador',
            fields=[
                ('id_ingredienteAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.administrador')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.carrinho')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ingrediente')),
            ],
        ),
    ]
