# Generated by Django 5.1.2 on 2024-10-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ingredientes', models.BooleanField(default=False)),
                ('utensilios', models.BooleanField(default=False)),
                ('morada', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('quantidade_stock', models.IntegerField()),
                ('unidade_medida', models.CharField(max_length=50)),
                ('limite_stock', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngredienteAdministrador',
            fields=[
                ('id_ingredienteAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngredienteValidade',
            fields=[
                ('id_ingredienteValidade', models.AutoField(primary_key=True, serialize=False)),
                ('data_validade', models.DateField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instucao',
            fields=[
                ('id_instucao', models.AutoField(primary_key=True, serialize=False)),
                ('numeroSequencia', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estimativaTempo', models.TimeField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utensilio',
            fields=[
                ('id_utensilio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('quantidade_stock', models.IntegerField()),
                ('limite_stock', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtensilioAdministrador',
            fields=[
                ('id_utensilioAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtensilioReceita',
            fields=[
                ('id_utensilioReceita', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
