# Generated by Django 5.1.2 on 2024-11-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utensilioreceita',
            table='utensilioreceita',
        ),
    ]
