# Generated by Django 5.1.2 on 2024-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinhos',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'carrinhos_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('vende_ingredientes', models.BooleanField(default=False)),
                ('vende_utensilios', models.BooleanField(default=False)),
                ('morada', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'fornecedores_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('quantidade_stock', models.IntegerField()),
                ('unidade_medida', models.CharField(max_length=50)),
                ('limite_stock', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ingredientes_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientesCarrinhos',
            fields=[
                ('id_ingrediente_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ingredientescarrinhos_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientesReceitas',
            fields=[
                ('id_ingrediente_receita', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrucoes',
            fields=[
                ('id_instrucao', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sequencia', models.IntegerField()),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'receitas_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utensilios',
            fields=[
                ('id_utensilio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('url_imagem', models.URLField(blank=True, null=True)),
                ('quantidade_stock', models.IntegerField()),
                ('limite_stock', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'utensilios_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtensiliosCarrinhos',
            fields=[
                ('id_utensilio_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'utensilioscarrinhos_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtensiliosReceitas',
            fields=[
                ('id_utensilio_receita', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='IngredienteCarrinho',
        ),
        migrations.DeleteModel(
            name='Instrucao',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
        migrations.DeleteModel(
            name='Utensilio',
        ),
        migrations.DeleteModel(
            name='UtensilioCarrinho',
        ),
        migrations.DeleteModel(
            name='UtensilioReceita',
        ),
    ]
