# Generated by Django 5.1.2 on 2024-11-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrucao',
            fields=[
                ('id_instrucao', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sequencia', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'instrucao',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Instucao',
        ),
        migrations.AlterModelTable(
            name='carrinho',
            table='carrinho',
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedor',
        ),
        migrations.AlterModelTable(
            name='ingrediente',
            table='ingrediente',
        ),
        migrations.AlterModelTable(
            name='receita',
            table='receita',
        ),
        migrations.AlterModelTable(
            name='utensilio',
            table='utensilio',
        ),
    ]
