# Generated by Django 4.1.13 on 2024-10-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMesa',
            fields=[
                ('id_estadoMesa', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estados_mesas',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.estadomesa')),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('online', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.cliente')),
                ('garcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.garcom')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.mesa')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id_pedidoProduto', models.AutoField(primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'db_table': 'pedidos_produtos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_hora_fim', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.mesa')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto_OpcaoItem',
            fields=[
                ('id_pedidoProduto_opcaoItem', models.AutoField(primary_key=True, serialize=False)),
                ('PedidoProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidoproduto')),
                ('opcaoItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.opcaoitem')),
            ],
            options={
                'db_table': 'pedidos_produtos_opcoes',
            },
        ),
    ]
