# Generated by Django 5.1.2 on 2024-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProdutoItemOpcao',
            fields=[
                ('id_pedido_produto_item_opcao', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'pedidoprodutoitemopcao',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PedidoProdutoOpcaoItem',
        ),
    ]
