CREATE TABLE IF NOT EXISTS cargos (
	id_cargo SERIAL PRIMARY KEY,
	designacao VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS utilizadores (
    id SERIAL PRIMARY KEY,
	id_cargo INT REFERENCES cargos(id_cargo) ON DELETE CASCADE,
	is_superuser BOOLEAN DEFAULT FALSE NOT NULL,
	is_anonymous BOOLEAN DEFAULT FALSE NOT NULL,
	is_authenticated BOOLEAN DEFAULT FALSE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
	username VARCHAR(50) UNIQUE NOT NULL,
	url_imagem VARCHAR(2048),
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    last_login TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
