# Generated by Django 4.1.13 on 2024-10-18 18:22

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUtilizador',
            fields=[
                ('id_tipo_utilizador', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_utilizador', models.AutoField(primary_key=True, serialize=False)),
                ('primeiro_nome', models.CharField(max_length=255)),
                ('ultimo_nome', models.CharField(max_length=255)),
                ('morada', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('data_registo', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='cargos_utilizador_groups', to='auth.group', verbose_name='groups')),
                ('tipo_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizadores', to='cargos.tipoutilizador')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizadores', to='cargos.turno')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cargos_utilizador_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrador', serialize=False, to='cargos.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente', serialize=False, to='cargos.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Cozinheiro',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cozinheiro', serialize=False, to='cargos.utilizador')),
                ('especialidades', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='garcom', serialize=False, to='cargos.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='GarcomIdioma',
            fields=[
                ('id_garcom_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=50)),
                ('garcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='cargos.garcom')),
            ],
        ),
    ]
