# Generated by Django 4.1.13 on 2024-10-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='administradores', to='inventario.fornecedor'),
        ),
    ]
