# Generated by Django 5.1.2 on 2024-11-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='data_registo',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='morada',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='ultimo_nome',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
