CREATE OR REPLACE PROCEDURE drop_tabelas() 
LANGUAGE plpgsql
AS $$
BEGIN
    DROP TABLE IF EXISTS Reserva;
    DROP TABLE IF EXISTS PedidoProdutoItemOpcao;
    DROP TABLE IF EXISTS PedidoProduto;
    DROP TABLE IF EXISTS Pedido;
    DROP TABLE IF EXISTS Servico;
    DROP TABLE IF EXISTS MenuDiaSemana;
    DROP TABLE IF EXISTS DiaSemana;
    DROP TABLE IF EXISTS ItemMenu;
    DROP TABLE IF EXISTS Menu;
    DROP TABLE IF EXISTS ItemOpcao;
    DROP TABLE IF EXISTS Opcao;
    DROP TABLE IF EXISTS ItemCategoria;
    DROP TABLE IF EXISTS Categoria;
    DROP TABLE IF EXISTS ItemTipo;
    DROP TABLE IF EXISTS Item;
    DROP TABLE IF EXISTS Tipo;
    DROP TABLE IF EXISTS Produto;
    DROP TABLE IF EXISTS Mesa;
    DROP TABLE IF EXISTS Instrucao;
    DROP TABLE IF EXISTS UtensilioReceita;
    DROP TABLE IF EXISTS IngredienteReceita;
    DROP TABLE IF EXISTS Receita;
    DROP TABLE IF EXISTS UtensilioCarrinho;
    DROP TABLE IF EXISTS Utensilio;
    DROP TABLE IF EXISTS IngredienteCarrinho;
    DROP TABLE IF EXISTS Ingrediente;
    DROP TABLE IF EXISTS Carrinho;
    DROP TABLE IF EXISTS Fornecedor;
    -- DROP TABLE IF EXISTS Utilizador;
    DROP TABLE IF EXISTS EstadoMesa;
END; 
$$;