DROP TABLE IF EXISTS reservas;
DROP TABLE IF EXISTS estadosreservas;
DROP TABLE IF EXISTS pedidosprodutos;
DROP TABLE IF EXISTS pedidos;
DROP TABLE IF EXISTS servicos;
DROP TABLE IF EXISTS mesas;
DROP TABLE IF EXISTS estadosmesas;