# Generated by Django 5.1.2 on 2024-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id_permissao', models.AutoField(primary_key=True, serialize=False)),
                ('designacao', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'permissoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissoesCargos',
            fields=[
                ('id_permissao_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'permissoescargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilizadoresCargos',
            fields=[
                ('id_utilizador_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'utilizadorescargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilizadoresPermissoes',
            fields=[
                ('id_utilizador_permissao', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'utilizadorespermissoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizadores',
            fields=[
                ('id_utilizador', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('turno_almoco', models.BooleanField(default=False)),
                ('turno_jantar', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telemovel', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cargos', models.ManyToManyField(related_name='utilizadores', through='autenticacao.UtilizadoresCargos', to='autenticacao.cargos')),
                ('permissoes', models.ManyToManyField(related_name='utilizadores', through='autenticacao.UtilizadoresPermissoes', to='autenticacao.permissoes')),
            ],
            options={
                'db_table': 'utilizadores',
            },
        ),
    ]
