# Generated by Django 5.1.2 on 2024-12-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissoes',
        ),
        migrations.DeleteModel(
            name='PermissoesCargos',
        ),
        migrations.DeleteModel(
            name='UtilizadoresPermissoes',
        ),
        migrations.AlterModelOptions(
            name='utilizadores',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='cargos',
            table='cargos_view',
        ),
        migrations.AlterModelTable(
            name='utilizadorescargos',
            table='utilizadorescargos_view',
        ),
    ]
