# Generated by Django 5.1.2 on 2024-11-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilizador',
            new_name='Utilizadores',
        ),
        migrations.AlterModelTable(
            name='utilizadores',
            table='utilizadores',
        ),
    ]
