# Generated by Django 5.1.2 on 2024-12-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_delete_permissoes_delete_permissoescargos_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilizadores',
            table='utilizadores_view',
        ),
    ]
