CREATE TABLE IF NOT EXISTS produtos (
	id_produto SERIAL PRIMARY KEY,
	item BOOLEAN DEFAULT FALSE NOT NULL,
	menu BOOLEAN DEFAULT FALSE NOT NULL,
	nome VARCHAR(100) NOT NULL,
	url_imagem VARCHAR(2048),
	preco DECIMAL(10, 2) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receitas (
	id_receita SERIAL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	duracao INTERVAL NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingredientesreceitas (
	id_ingrediente_receita SERIAL PRIMARY KEY,
	id_ingrediente INT REFERENCES ingredientes(id_ingrediente) ON DELETE CASCADE,
	id_receita INT REFERENCES receitas(id_receita) ON DELETE CASCADE,
	quantidade INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS utensiliosreceitas (
	id_utensilio_receita SERIAL PRIMARY KEY,
	id_utensilio INT REFERENCES utensilios(id_utensilio) ON DELETE CASCADE,
	id_receita INT REFERENCES receitas(id_receita) ON DELETE CASCADE,
	quantidade INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instrucoes (
	id_instrucao SERIAL PRIMARY KEY,
	id_receita INT REFERENCES receitas(id_receita) ON DELETE CASCADE,
	numero_sequencia INT NOT NULL,
	descricao TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT unique_instrucao UNIQUE (id_receita, numero_sequencia)
);

CREATE TABLE IF NOT EXISTS tipos (
	id_tipo SERIAL PRIMARY KEY,
	designacao VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itens (
	id_item INT PRIMARY KEY REFERENCES produtos(id_produto) ON DELETE CASCADE,
	porcao_unidade_medida VARCHAR(50) NOT NULL,
	porcao INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itenstipos (
	id_item_tipo SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_tipo INT REFERENCES tipos(id_tipo) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias (
	id_categoria SERIAL PRIMARY KEY,
	designacao VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itenscategorias (
	id_item_categoria SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_categoria INT REFERENCES categorias(id_categoria) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS opcoes (
	id_opcao SERIAL PRIMARY KEY,
	designacao VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itensopcoes (
	id_item_opcao SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_opcao INT REFERENCES opcoes(id_opcao) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS menus (
	id_menu INT PRIMARY KEY REFERENCES produtos(id_produto) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS itensmenus (
	id_item_menu SERIAL PRIMARY KEY,
	id_item INT REFERENCES itens(id_item) ON DELETE CASCADE,
	id_menu INT REFERENCES menus(id_menu) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS diassemana (
	id_dia_semana SERIAL PRIMARY KEY,
	designacao VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS menusdiassemana (
	id_menu_dia_semana SERIAL PRIMARY KEY,
	id_menu INT REFERENCES menus(id_menu) ON DELETE CASCADE,
	id_dia_semana INT REFERENCES diassemana(id_dia_semana) ON DELETE CASCADE,
	almoco BOOLEAN DEFAULT FALSE NOT NULL,
	jantar BOOLEAN DEFAULT FALSE NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);